version: 0.0
os: windows
files:
  - source: \PipelineTesting
    destination: C:\WebApi
hooks:
  BeforeInstall:
    - location: C:\ApplicationPipeline\Apiprojectdeployment\install-prerequisites.ps1
      timeout: 900
  ApplicationStart:
    - location: C:\ApplicationPipeline\Apiprojectdeployment\start-webapi.ps1
      timeout: 900
