version: 0.0
os: windows
files:
  - source: .
    destination: C:\WebApiFolder
hooks:
  BeforeInstall:
    - location:scripts\install-prerequisites.ps1
      timeout: 900
  ApplicationStart:
    - location:scripts\start-webapi.ps1
      timeout: 900
