version: 0.0
os: windows
files:
  - source: /
    destination: C:\MyCicdApplication
hooks:
  BeforeInstall:
    - location: scripts/install-prerequisites.ps1
      timeout: 1800
  ApplicationStart:
    - location: scripts\install-prerequisites.ps1
      timeout: 1800
