version: 0.0
os: windows
files:
  - source: .
    destination: C:\MyCicdApplication
hooks:
  BeforeInstall:
    - location: Scripts/install-prerequisites.ps1
      timeout: 1800
  ApplicationStart:
    - location: Scripts/start-webapi.ps1
      timeout: 1800
